### ISSUE TITLE
Add custom=true support to ReportOptions in RequestReport

### ISSUE THREAD

**Issue by alisanalacam** [keithbrink/amazon-mws-laravel#18]

**Comment by keithbrink** [comment]
Can you provide some more detail about why this is needed?

**Comment by alisanalacam** [comment]
first, thank you for reply.

I want to be able to send the parameter named 'custom' for ReportOptions

https://docs.developer.amazonservices.com/en_UK/reports/Reports_ReportType.html
example: 
Enumeration value: _GET_MERCHANT_LISTINGS_ALL_DATA_

I can add like this:
$this->options['ReportOptions=custom'] = 'true';

**Comment by keithbrink** [comment]
OK, in version 7.0.3 you can do:

```
$report->setCustomReport(true);
```
