### ISSUE TITLE
Cannot access to MarketplaceId

### ISSUE THREAD

**Issue by erayalakese** [keithbrink/amazon-mws-laravel#33]
I'm trying to register my SQS as a destination to my subscription.

```
$config = [
            'merchantId' => 'A**', 
            'marketplaceId' => 'A2***',
            'keyId' => 'AKIA****',
            'secretKey' => 'jl***',
            'mwsAuthToken' => 'amzn.mws.fcb***',
            'amazonServiceUrl' => 'https://mws.amazonservices.ae/',
        ];
$amz = new AmazonOrderList('default');
$amz->setConfig($config);
        $amz->setDeliveryChannel("SQS");
        $amz->setMarketplace($config['marketplaceId']);
        $amz->setAttributes(["sqsQueueUrl" =>"URL_OF_SQS");
        var_dump($amz->registerDestination());
```

But `$amz->registerDestination()` returning `false` and according to Laravel logs:

```
[2020-05-11 21:42:06] local.ERROR: Marketplace ID is missing  
[2020-05-11 21:42:06] local.INFO: Making request to Amazon: RegisterDestination  
[2020-05-11 21:42:07] local.ERROR: Bad Response! 404 Not Found: InvalidAddress - Resource / is not found on this server. API Section is missing or you have provided an invalid operation name.  
```

The error log directly coming from AmazonSubscriptionCore.php line 64

```
if (isset($store[$this->storeName]['marketplaceId'])) {
            $this->setMarketplace($store[$this->storeName]['marketplaceId']);
        } else {
            $this->log('Marketplace ID is missing', 'Urgent');
        }
```

Looks like `$store` variable is not defined in the function.

**Comment by erayalakese** [comment]
After digging out the code, I figured out there are two different bugs here. First one is the one with `Marketplace ID is missing`. Cause of the issue is `$store` variable is not defined in the AmazonSubscriptionCore. But no idea, how to fix it properly. 

The second issue, `404 Not Found`. `$AMAZON_VERSION_SUBSCRIBE = '2013-07-01';` was missing in the environment.php file and because of it, AmazonSubscriptionCore.php won't be able to define `urlbranch`.

```
if (isset($AMAZON_VERSION_SUBSCRIBE)) {
            $this->urlbranch = 'Subscriptions/'.$AMAZON_VERSION_SUBSCRIBE;
            $this->options['Version'] = $AMAZON_VERSION_SUBSCRIBE;
        }
```

This PR should fix this second issue : https://github.com/keithbrink/amazon-mws-laravel/pull/34

@keithbrink

**Comment by keithbrink** [comment]
Can you try again with version 7.1.3 - I think your PR fixed the main problem.
