### ISSUE TITLE
AmazonOrderList returns empty array

### ISSUE THREAD

**Issue by allanshelly** [keithbrink/amazon-mws-laravel#41]
AmazonOrderList returns empty array when used as an API end point for a laravel app

**Comment by allanshelly** [comment]
public function getAmazonOrders() {
        ini_set('max_execution_time', 1444);
        $amz = new AmazonOrderList("rockymountainoils");
        $amz->setLimits('Modified', "- 720 hours");
        $amz->setUseToken();
        $amz->fetchOrders();
        return $amz->getList();
    }

this function returns the following
![image](https://user-images.githubusercontent.com/16277368/86598109-3b2a8800-bfcf-11ea-89fe-ec3f2f60915f.png)

**Comment by allanshelly** [comment]
fairly new to php and laravel in general. but there are no viable resources for laravel mws integration besides this repo and would love to receive some guidance of what im doing wrong

**Comment by keithbrink** [comment]
You need to get the data from each order:


```php
$order_list = new AmazonOrderList(....);
...
$orders = $order_list->getList();
foreach($orders as $order) {
    $order_data = $order->getData();
}
```
