### ISSUE TITLE
SalesRankings issue

### ISSUE THREAD

**Issue by discover59** [keithbrink/amazon-mws-laravel#47]
I use AmazonProductList to get matching products by id.
It's limited to use at most 5 ids at a time. Is there method to use GetMatchingProduct which requires ASIN? It's helpful as it can request up to 10 products at a time.

Also fetchProductList returns only one salesrankings for given product.
There are other salesrankings on scratchpad.

Please let me know whether it's possible to achieve all above.

**Comment by keithbrink** [comment]
You should be able to do `setIdType('ASIN')` to change the ID type on the AmazonProductList.

Can you use `getRawResponses` and post the raw response from Amazon on the `fetchProductList` function? Make sure you remove sensitive info.

**Comment by discover59** [comment]
I tried to use `ASIN` type but max id count is 5. I want to use GetMatchingProduct api which can get up to 10 products at a time.

**Comment by keithbrink** [comment]
I see - you can use the `AmazonProductInfo` class to send a `GetMatchingProduct` request.
