### ISSUE TITLE
Unrecognized Response: Array, could not resolve

### ISSUE THREAD

**Issue by GeneralWiggles** [keithbrink/amazon-mws-laravel#48]
Hello! Thanks for updating this package, really saved me some time. Currently, I'm screwing around with it in Laravel and I am getting this error below.

I am not sure what is causing it. I am currently just trying to test grabbing a MatchingProductById. I double checked all of my Keys and they are fine, my end URL is also fine. Here is my Controller code of what I am trying to call. 

Any helpful hints are greatly appreciated! 

```
"[2021-01-18 15:52:57] local.INFO: Making request to Amazon: GetMatchingProductForId  
[2021-01-18 15:52:57] local.INFO: Unrecognized response: Array
(
    [ok] => -1
    [error] => Could not resolve host: mws.amazonservices.comProducts
)
  
[2021-01-18 15:52:57] local.NOTICE: No Response found  "
```

```

<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;
use KeithBrink\AmazonMws\AmazonInventoryList;
use KeithBrink\AmazonMws\AmazonOrderList;
use KeithBrink\AmazonMws\AmazonProduct;
use KeithBrink\AmazonMws\AmazonProductsCore;
use KeithBrink\AmazonMws\AmazonProductList;


class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
    public function index(){
        return view('index');
    }
    public function test()
    {
        $obj = new AmazonProductList('store1');
        $obj->setIdType('ASIN');
        $obj->setProductIds('1285741552');
        $obj->fetchProductList();
        return $obj->getProduct('1285741552');
        

    
    }
}
```

**Comment by keithbrink** [comment]
Hey there, some helpful debugging tools are the `getRawResponses` method (the raw result from Amazon) and the `getOptions` method (exactly what is being sent to Amazon). Can you have at what that returns and see if that gives any clues into what the issue might be?

**Comment by keithbrink** [comment]
You might also want to check that your `amazonServiceUrl` in your settings has a trailing slash.

**Comment by GeneralWiggles** [comment]
You know, I was that dumb person that did not put a trailing slash. That Solved that! So The slash solved the Original error I was getting, but now it only returns [{"muteLog":false}]

When I check the logs It has no inherent errors, it is just saying [2021-01-18 16:16:30] local.INFO: Making request to Amazon: GetMatchingProductForId

**Comment by keithbrink** [comment]
The `getProduct` method accepts an index rather than the product ID, and I believe you need to call `getData` on the product, so something like this:

```php
return $obj->getProduct(0)->getData();
```

**Comment by GeneralWiggles** [comment]
Heck yeah it works! Thanks for the help!

**Comment by keithbrink** [comment]
No problem!
