### ISSUE TITLE
Multiple GetProductByIds

### ISSUE THREAD

**Issue by GeneralWiggles** [keithbrink/amazon-mws-laravel#49]
Hello, 

Is there anyway the package to display multiple products?

Here is an example: 

This ISBN: 9781285741550 Renders 3 different entries in scratchpad. Currently, the program would only display the first one via the getProduct(0) and you would have to input a 1 or a 2 to see the other entries. Is there a way to show them all at once?

**Comment by keithbrink** [comment]
Hey there, happy to help with bugs/feature improvements, but this falls more into the support category which I'm unable to give time to.
