### ISSUE TITLE
Missing merchant version in environment file

### ISSUE THREAD

**Issue by shanijahania** [keithbrink/amazon-mws-laravel#53]
I am working on merchant section to get "**GetEligibleShippingServices**" using the "**AmazonMerchantServiceList**" Class in the library and i found that the environment variable "**AMAZON_VERSION_MERCHANT**" that is being used in AmazonMerchantCore class line 28 is missing in environment file. 
Can you please add this variable to environment file.

Thanks

**Comment by keithbrink** [comment]
Feel free to send a PR.
